### ISSUE TITLE
TO-DO content in EnergySystemsRiley

### ISSUE THREAD

**Issue by R-Y-M-R** [ConfederationC/Project_2018#57]
Complete and check off the following to complete the branch...

- [x] Expand Procedures section up to the point of the chosen 2 systems.
- [x] Expand Reasoning section to include Solar energy.
- [x] Integrate [wind farm area, configurations](https://www.saskwind.ca/land-area) into Area section.
- [x] Finish the descriptions of energy options in the energy-options table.
- [x] Use APA citations.
- [x] Grammar check.
- [x] Use 'Dkal' more.

**Comment by ByounghyunOh** [comment]
Both done, you can merge [my branch](https://github.com/ConfederationC/Project_2018/tree/EnergySystems) to yours.
- Expand Reasoning section to include Solar energy.
- Finish the descriptions of energy options in the energy-options table.

We may don't need to really strictly using APA format as long as we include the references.

**Comment by R-Y-M-R** [comment]
Finished the rest, made a references folder with our refs in a text file.
